#---------------------------------------------------------------------------
# Copyright IBM Corp. 2015, 2015 All Rights Reserved
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# Limitations under the License.
#---------------------------------------------------------------------------

- stat: path={{ swift_install_reop_dir }}
  register: inst_dir
- file: path={{ swift_install_reop_dir }} state=directory recurse=yes
  when: not inst_dir.stat.exists

- name: clone swift_install repo
  stat: path="{{ swift_install_reop_dir }}/{{swift_install_repo_name}}"
  register: repo_dir

- git: repo={{ swift_install_repo_url }}
       dest={{ swift_install_reop_dir }}/{{ swift_install_repo_name }}
       version={{  swift_install_repo_branch }}
  when: not repo_dir.stat.exists

- name: clone openstack ansible libraries (for keystone configuration)
  git: repo=https://github.com/openstack-ansible/openstack-ansible-modules.git
       dest={{ swift_install_reop_dir }}/{{ swift_install_repo_name }}/provisioning/openstack-ansible-modules
       version="HEAD"

- name: Copy cluster_config.json to the swift install location
  shell: cp /tmp/cluster_config.json "{{ swift_install_reop_dir }}/{{ swift_install_repo_name }}/provisioning/cluster_config.json"

- file: mode=1777 path="{{ swift_install_reop_dir }}/{{swift_install_repo_name}}"
